SELECT 'Cleaning the database' AS Status;
--RUNCATE TABLE avaliacao RESTART IDENTITY CASCADE;
--TRUNCATE TABLE reserva RESTART IDENTITY CASCADE;
--TRUNCATE TABLE restaurante RESTART IDENTITY CASCADE;
--TRUNCATE TABLE endereco RESTART IDENTITY CASCADE;
--TRUNCATE TABLE cidade RESTART IDENTITY CASCADE;
--TRUNCATE TABLE estado RESTART IDENTITY CASCADE;

DELETE FROM avaliacao RESTART;
DELETE FROM reserva RESTART;
DELETE FROM restaurante RESTART;
DELETE FROM endereco RESTART;
DELETE FROM cidade RESTART;
DELETE FROM estado RESTART;